"""Export pinned Apache-2.0 libphonenumber metadata; no network at generation time."""
import json
import pathlib
import re
import hashlib
import phonenumbers as p
from phonenumbers import PhoneMetadata

ROOT = pathlib.Path(__file__).resolve().parents[1]
if p.__version__ != "8.13.52":
    raise SystemExit("Install phonenumbers==8.13.52; metadata updates require an explicit review")

def q(s):
    return json.dumps(s or "", ensure_ascii=False)

def replacement(s):
    return re.sub(r"\\(\d)", r"$\1", s or "")

def desc(d):
    if d is None:
        return '{ pattern: "", lengths: [], local_lengths: [], example: "" }'
    return '{ pattern: %s, lengths: %s, local_lengths: %s, example: %s }' % (
        q(d.national_number_pattern), list(d.possible_length), list(d.possible_length_local_only), q(d.example_number))

def fmt(f):
    return '{ pattern: %s, replacement: %s, leading: %s, prefix_rule: %s, prefix_optional: %s, carrier_rule: %s }' % (
        q(f.pattern), q(replacement(f.format)), json.dumps(f.leading_digits_pattern),
        q(replacement(f.national_prefix_formatting_rule)), str(bool(f.national_prefix_optional_when_formatting)).lower(),
        q(replacement(f.domestic_carrier_code_formatting_rule)))

types = [('FixedLine','fixed_line'),('Mobile','mobile'),('TollFree','toll_free'),('PremiumRate','premium_rate'),
         ('SharedCost','shared_cost'),('Voip','voip'),('PersonalNumber','personal_number'),('Pager','pager'),('Uan','uan'),('Voicemail','voicemail')]
regions=[]
for cc, rr in sorted(p.COUNTRY_CODE_TO_REGION_CODE.items()):
    for r in rr:
        md = PhoneMetadata.metadata_for_nongeo_region(cc) if r == '001' else PhoneMetadata.metadata_for_region(r)
        key = '001-%s' % cc if r == '001' else r
        regions.append((key,md))
lines=['// GENERATED by scripts/export_metadata.py; Apache-2.0 upstream metadata. DO NOT EDIT.', '///|', 'let region_order : Array[String] = '+json.dumps([k for k,m in regions]), '///|', 'let metadata_table : Map[String, Metadata] = {']
for key,m in regions:
    lines.append('%s: metadata_%s(),' % (q(key), key.replace('-','_')))
lines.append('}')
for key,m in regions:
    lines += ['///|','fn metadata_%s() -> Metadata {' % key.replace('-','_'), '{',
        'region: %s, code: %d,' % (q(m.id),m.country_code),
        'international_prefix: %s, preferred_international_prefix: %s,' % (q(m.international_prefix),q(m.preferred_international_prefix)),
        'national_prefix: %s, prefix_pattern: %s, prefix_transform: %s,' % (q(m.national_prefix),q(m.national_prefix_for_parsing),q(replacement(m.national_prefix_transform_rule))),
        'leading: %s, main_region: %s,' % (q(m.leading_digits),str(bool(m.main_country_for_code)).lower()),
        'general: %s,' % desc(m.general_desc),
        'types: [%s],' % ','.join('(%s, %s)'%(t,desc(getattr(m,a))) for t,a in types),
        'formats: [%s],' % ','.join(fmt(f) for f in m.number_format),
        'international_formats: [%s],' % ','.join(fmt(f) for f in m.intl_number_format),
        'extension_prefix: %s,' % q(m.preferred_extn_prefix),
        'no_international: %s,' % desc(m.no_international_dialling), '}', '}']
text='\n'.join(lines)+'\n'
(ROOT/'metadata_generated.mbt').write_text(text,encoding='utf-8')
manifest={'upstream':'python-phonenumbers','version':p.__version__,'regions':len(p.SUPPORTED_REGIONS),'non_geographic_codes':len(p.COUNTRY_CODES_FOR_NON_GEO_REGIONS),'records':len(regions),'sha256_unformatted':hashlib.sha256(text.encode()).hexdigest(),'license':'Apache-2.0'}
(ROOT/'metadata'/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
print(manifest)
